# Generated by Django 4.2.7 on 2023-12-02 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarApp', '0002_customuser_customer_customuser_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='analysis_requests',
            field=models.IntegerField(default=0),
        ),
    ]
