# Generated by Django 4.2.7 on 2023-12-10 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0002_initial'),
        ('solarApp', '0003_customuser_analysis_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='djstripe.product'),
        ),
    ]
