# Generated by Django 4.2.7 on 2023-12-10 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarApp', '0004_customuser_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='max_analysis_requests',
            field=models.IntegerField(default=3),
        ),
    ]
